spring:
  datasource:
    url: jdbc:sqlserver://listapp-sql-server-test1.database.windows.net:1433;database=listapp-db-test1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: user
    password: pass@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

#spring:
#  datasource:
#    url: ${listapp.db.url}
#    username: ${listapp.db.username}
#    password: ${listapp.db.password}
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
