#spring:
#  datasource:
#    url: jdbc:sqlserver://listapp-sql-server-test.database.windows.net:1433;database=listapp-db-test;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: user
#    password: pass@123
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect

#server:
#  port: 9191
#
spring:
  datasource:
    url: ${listapp.db.url}
    username: ${listapp.db.username}
    password: ${listapp.db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

#server:
#  port: 9191